/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    'team-members': TeamMember;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Benutzer mit Zugriff auf das Admin-Panel. Jeder Benutzer hat eine Rolle (Admin oder Editor).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admin: voller Zugriff. Editor: kann Inhalte bearbeiten, aber keine Einstellungen ändern.
   */
  role: 'admin' | 'editor';
  /**
   * Vorname des Benutzers.
   */
  firstName?: string | null;
  /**
   * Nachname des Benutzers.
   */
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Bilder und Dokumente. Alle Dateien werden auf Ihrem eigenen AWS S3 gespeichert.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternativtext für Barrierefreiheit und SEO. Beschreiben Sie kurz, was auf dem Bild zu sehen ist.
   */
  alt: string;
  /**
   * Optionale Bildunterschrift.
   */
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Verwalten Sie Ihre Website-Seiten. Jede Seite hat eine eigene URL (Slug) und kann mit Layout-Blöcken oder Freitext gestaltet werden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-Pfad der Seite (z.B. 'leistungen' für /leistungen). Wird automatisch in der Adresszeile verwendet.
   */
  slug: string;
  /**
   * Optionales Titelbild für die Seite.
   */
  heroImage?: (number | null) | Media;
  /**
   * Seitenlayout mit Inhaltsblöcken. Nutzen Sie dies für strukturierte Seiten wie die Startseite. Blöcke können per Drag & Drop angeordnet werden.
   */
  layout?:
    | (
        | {
            headline: string;
            subheadline?: string | null;
            primaryCta: {
              label: string;
              url: string;
            };
            secondaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            headline: string;
            subheadline?: string | null;
            services?:
              | {
                  title: string;
                  description: string;
                  /**
                   * Icon name (e.g. palette, code, megaphone, pen-tool)
                   */
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            headline: string;
            subheadline?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'portfolio';
          }
        | {
            headline: string;
            testimonials?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  company?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            headline: string;
            description?: string | null;
            buttonLabel: string;
            buttonUrl: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richtext';
          }
        | {
            headline: string;
            subheadline?: string | null;
            /**
             * Pick specific members, or leave empty to show all.
             */
            members?: (number | TeamMember)[] | null;
            /**
             * Max members to display (0 = all).
             */
            limit?: number | null;
            /**
             * Show link to the full /team page.
             */
            showLink?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
      )[]
    | null;
  /**
   * Freitext-Inhalt mit dem Rich-Text-Editor. Nutzen Sie dies für einfache Seiten wie Über uns oder Kontakt.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    /**
     * Überschreibt den Seitentitel für Suchmaschinen. Leer lassen, um den Seitentitel zu verwenden.
     */
    title?: string | null;
    /**
     * Kurzbeschreibung für Suchmaschinen (max. 160 Zeichen). Erscheint in Google-Ergebnissen.
     */
    description?: string | null;
    /**
     * Bild das beim Teilen auf Social Media angezeigt wird (Open Graph).
     */
    image?: (number | null) | Media;
  };
  /**
   * Veröffentlichungsdatum. Wird automatisch gesetzt, wenn der Status auf 'Published' geändert wird.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Team members displayed on the website. Drag the "order" field to control sort order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * URL path (e.g. "max-mustermann" for /team/max-mustermann).
   */
  slug: string;
  /**
   * Job title or role, e.g. "Lead Developer" or "CEO".
   */
  role: string;
  /**
   * Portrait photo. Recommended: square, min 400x400px.
   */
  photo?: (number | null) | Media;
  /**
   * One-liner shown on the team overview card.
   */
  excerpt?: string | null;
  /**
   * Full biography shown on the detail page.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Contact email (optional).
   */
  email?: string | null;
  /**
   * Phone number (optional).
   */
  phone?: string | null;
  /**
   * Social media and website links.
   */
  socialLinks?:
    | {
        platform: 'linkedin' | 'xing' | 'twitter' | 'github' | 'instagram' | 'website';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Allows filtering by department.
   */
  department?: ('management' | 'development' | 'design' | 'marketing') | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  meta?: {
    /**
     * SEO title override.
     */
    title?: string | null;
    /**
     * SEO description (max 160 characters).
     */
    description?: string | null;
    /**
     * Open Graph image.
     */
    image?: (number | null) | Media;
  };
  /**
   * Auto-set when status changes to published.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Blog-Beiträge und Artikel. Schreiben Sie regelmäßig, um bei Suchmaschinen besser gefunden zu werden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-Pfad des Beitrags (z.B. 'mein-erster-post' für /blog/mein-erster-post).
   */
  slug: string;
  /**
   * Vorschaubild für den Beitrag. Wird in der Blog-Übersicht und beim Teilen angezeigt.
   */
  heroImage?: (number | null) | Media;
  /**
   * Kurze Zusammenfassung für die Blog-Übersicht. 1-2 Sätze die neugierig machen.
   */
  excerpt?: string | null;
  /**
   * Der Hauptinhalt des Beitrags. Nutzen Sie Überschriften, Listen und Bilder für bessere Lesbarkeit.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Kategorie für die Filterung und Organisation Ihrer Beiträge.
   */
  category?: ('blog' | 'news' | 'case-study') | null;
  /**
   * Verfasser des Beitrags. Wählen Sie einen registrierten Benutzer aus.
   */
  author?: (number | null) | User;
  meta?: {
    /**
     * SEO-Titel für Suchmaschinen. Leer = Beitragstitel wird verwendet.
     */
    title?: string | null;
    /**
     * SEO-Beschreibung (max. 160 Zeichen).
     */
    description?: string | null;
    /**
     * Social-Media-Vorschaubild (Open Graph).
     */
    image?: (number | null) | Media;
  };
  /**
   * Veröffentlichungsdatum. Wird automatisch gesetzt bei Statuswechsel auf 'Published'.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              services?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        portfolio?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              headline?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    company?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              headline?: T;
              description?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        richtext?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              members?: T;
              limit?: T;
              showLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  author?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  photo?: T;
  excerpt?: T;
  bio?: T;
  email?: T;
  phone?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  department?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Bearbeiten Sie hier die Navigation Ihrer Website. Änderungen werden sofort auf allen Seiten sichtbar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  /**
   * Navigationslinks in der Kopfzeile. Maximal 8 Einträge. Reihenfolge per Drag & Drop ändern.
   */
  navItems?:
    | {
        /**
         * Angezeigter Text des Links.
         */
        label: string;
        /**
         * Ziel-URL (z.B. /leistungen oder https://example.com).
         */
        url: string;
        /**
         * Link in neuem Tab öffnen (empfohlen für externe Links).
         */
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optionaler hervorgehobener Button rechts in der Navigation.
   */
  ctaButton?: {
    /**
     * Button ein- oder ausblenden.
     */
    enabled?: boolean | null;
    /**
     * Button-Text (z.B. 'Kontakt' oder 'Angebot anfordern').
     */
    label?: string | null;
    /**
     * Ziel-URL des Buttons.
     */
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Fußzeile Ihrer Website. Organisieren Sie Links in Spalten und fügen Sie Social-Media-Profile hinzu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Link-Spalten im Footer. Maximal 4 Spalten mit je bis zu 6 Links.
   */
  columns?:
    | {
        /**
         * Überschrift der Spalte (z.B. 'Unternehmen', 'Leistungen').
         */
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright-Text am unteren Rand (z.B. '© 2026 Meine Firma').
   */
  copyright?: string | null;
  /**
   * Social-Media-Profile. Werden als Icons im Footer angezeigt.
   */
  socialLinks?:
    | {
        platform: 'linkedin' | 'twitter' | 'instagram' | 'github' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Globale Einstellungen für Ihre Website. Änderungen wirken sich auf die gesamte Seite aus.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Visuelles Theme der Website. Änderungen werden sofort auf allen Seiten sichtbar — kein erneutes Deployment nötig.
   */
  theme: 'minimal' | 'bold' | 'corporate';
  /**
   * Name Ihrer Website. Wird im Browser-Tab und in Suchmaschinen angezeigt.
   */
  siteName: string;
  /**
   * Standard-Beschreibung für Suchmaschinen. Wird verwendet, wenn eine Seite keine eigene Beschreibung hat.
   */
  siteDescription?: string | null;
  /**
   * Kleines Icon im Browser-Tab. Empfohlen: 32x32 Pixel, PNG oder ICO.
   */
  favicon?: (number | null) | Media;
  /**
   * Standard-Bild beim Teilen auf Social Media. Empfohlen: 1200x630 Pixel.
   */
  ogImage?: (number | null) | Media;
  /**
   * Drittanbieter-Analyse-Integration.
   */
  analytics?: {
    /**
     * Google Analytics Measurement ID (z.B. G-XXXXXXXXXX). Leer lassen, wenn Sie kein Google Analytics verwenden.
     */
    googleAnalyticsId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        enabled?: T;
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  theme?: T;
  siteName?: T;
  siteDescription?: T;
  favicon?: T;
  ogImage?: T;
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}